server:
  port: 8081

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rabbitmq-demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 是否启用【发布确认】，默认false，回调 p -> Exchange
    publisher-confirms: true
    # 是否启用【发布返回】，默认false，回调 message -> Queue
    publisher-returns: true
    listener:
      simple:
        # 表示消息确认方式，其有三种配置方式，分别是none、manual和auto；默认auto
        acknowledge-mode: manual # 开启手动确认模式
        # 一个消费者最多可处理的nack消息数量，如果有事务的话，必须大于等于transaction数量.
        prefetch: 100
  mail:
    host: smtp.163.com
    username: qiujianp123@163.com
    password: HKTYEJZPOGHVXOWC
    from: build-flat@foxmail.com  # 定向发送的邮件用户
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true
          required: true
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.qjp.rabbit.demo02.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

    rabbitmq:
      exchanges:
        - name: notify.logisticPushDelay
          delayed: true
          queues:
            - name: notify.request.logictic
              priority: 100